name: shell commands

on: [push]


jobs: 
 run-shell-command:
  runs-on: ubuntu-latest
  needs: ["run-windows-commands"]
  steps:
    - name: checkout 
      uses: actions/checkout@v2
    - name: echo string
      run: echo  "Hello Boina"
    - name: Multiline script
      run: |
        node -v
        pwd
 run-windows-commands:
   runs-on: windows-latest
   steps:
    - name: Directory
      run: Get-Location
    - name: Directory using bash
      run: pwd
      shell: bash